artifacts:
  gluc_raw:
    path: data/datasets/validation_datasets/gluc_raw.ipc
    type: dataset
  gluc_labelled:
    path: data/datasets/validation_datasets/gluc_labelled.ipc
    type: dataset
  hela_qc_raw:
    path: data/datasets/validation_datasets/hela_qc_raw.ipc
    type: dataset
  hela_qc_labelled:
    path: data/datasets/validation_datasets/hela_qc_labelled.ipc
    type: dataset
  herceptin_raw:
    path: data/datasets/validation_datasets/herceptin_raw.ipc
    type: dataset
  herceptin_labelled:
    path: data/datasets/validation_datasets/herceptin_labelled.ipc
    type: dataset
  immuno_subset_raw:
    path: data/datasets/validation_datasets/immuno_subset_raw.ipc
    type: dataset
  immuno_subset_labelled:
    path: data/datasets/validation_datasets/immuno_subset_labelled.ipc
    type: dataset
  s_brodae_raw:
    path: data/datasets/validation_datasets/s_brodae_raw.ipc
    type: dataset
  s_brodae_labelled:
    path: data/datasets/validation_datasets/s_brodae_labelled.ipc
    type: dataset
  snake_venoms_raw:
    path: data/datasets/validation_datasets/snake_venoms_raw.ipc
    type: dataset
  snake_venoms_labelled:
    path: data/datasets/validation_datasets/snake_venoms_labelled.ipc
    type: dataset
  tpl_antibodies_raw:
    path: data/datasets/validation_datasets/tpl_antibodies_raw.ipc
    type: dataset
  tpl_antibodies_labelled:
    path: data/datasets/validation_datasets/tpl_antibodies_labelled.ipc
    type: dataset
  wound_fluids_raw:
    path: data/datasets/validation_datasets/wound_fluids_raw.ipc
    type: dataset
  wound_fluids_labelled:
    path: data/datasets/validation_datasets/wound_fluids_labelled.ipc
    type: dataset

stages:
  predict:
    foreach:
      gluc_raw:
        checkpoint: data/checkpoints/instanovo.pt
        knapsack: data/knapsacks/mass_scale_10000_max_mass_4000
        dataset: data/datasets/validation_datasets/gluc_raw.ipc
      gluc_labelled:
        checkpoint: data/checkpoints/instanovo.pt
        knapsack: data/knapsacks/mass_scale_10000_max_mass_4000
        dataset: data/datasets/validation_datasets/gluc_labelled.ipc
      hela_qc_raw:
        checkpoint: data/checkpoints/instanovo.pt
        knapsack: data/knapsacks/mass_scale_10000_max_mass_4000
        dataset: data/datasets/validation_datasets/hela_qc_raw.ipc
      hela_qc_labelled:
        checkpoint: data/checkpoints/instanovo.pt
        knapsack: data/knapsacks/mass_scale_10000_max_mass_4000
        dataset: data/datasets/validation_datasets/hela_qc_labelled.ipc
      herceptin_raw:
        checkpoint: data/checkpoints/instanovo.pt
        knapsack: data/knapsacks/mass_scale_10000_max_mass_4000
        dataset: data/datasets/validation_datasets/herceptin_raw.ipc
      herceptin_labelled:
        checkpoint: data/checkpoints/instanovo.pt
        knapsack: data/knapsacks/mass_scale_10000_max_mass_4000
        dataset: data/datasets/validation_datasets/herceptin_labelled.ipc
      immuno_subset_raw:
        checkpoint: data/checkpoints/instanovo.pt
        knapsack: data/knapsacks/mass_scale_10000_max_mass_4000
        dataset: data/datasets/validation_datasets/immuno_subset_raw.ipc
      immuno_subset_labelled:
        checkpoint: data/checkpoints/instanovo.pt
        knapsack: data/knapsacks/mass_scale_10000_max_mass_4000
        dataset: data/datasets/validation_datasets/immuno_subset_labelled.ipc
      s_brodae_raw:
        checkpoint: data/checkpoints/instanovo.pt
        knapsack: data/knapsacks/mass_scale_10000_max_mass_4000
        dataset: data/datasets/validation_datasets/s_brodae_raw.ipc
      s_brodae_labelled:
        checkpoint: data/checkpoints/instanovo.pt
        knapsack: data/knapsacks/mass_scale_10000_max_mass_4000
        dataset: data/datasets/validation_datasets/s_brodae_labelled.ipc
      snake_venoms_raw:
        checkpoint: data/checkpoints/instanovo.pt
        knapsack: data/knapsacks/mass_scale_10000_max_mass_4000
        dataset: data/datasets/validation_datasets/snake_venoms_raw.ipc
      snake_venoms_labelled:
        checkpoint: data/checkpoints/instanovo.pt
        knapsack: data/knapsacks/mass_scale_10000_max_mass_4000
        dataset: data/datasets/validation_datasets/snake_venoms_labelled.ipc
      wound_fluids_raw:
        checkpoint: data/checkpoints/instanovo.pt
        knapsack: data/knapsacks/mass_scale_10000_max_mass_4000
        dataset: data/datasets/validation_datasets/wound_fluids_raw.ipc
      wound_fluids_labelled:
        checkpoint: data/checkpoints/instanovo.pt
        knapsack: data/knapsacks/mass_scale_10000_max_mass_4000
        dataset: data/datasets/validation_datasets/wound_fluids_labelled.ipc
    do:
      cmd:
        python -m instanovo.transformer.predict --data-path ${item.dataset} --model-path
        ${item.checkpoint} --output-path
        data/predictions/instanovo/validation_instanovo_knapsack_${key}_kpreds.csv  --knapsack-path
        ${item.knapsack}
      outs:
        - data/predictions/instanovo/validation_instanovo_knapsack_${key}_kpreds.csv
