# yaml-language-server: $schema=https://instadeep.aichor.ai/schema/latest/manifest.schema.json
kind: AIchorManifest
apiVersion: 0.2.1
builder:
  image: instanovo
  dockerfile: ./Dockerfile
  context: .
  buildArgs:
    USE_CUDA: "true"
spec:
  operator: tf
  image: instanovo
  command: make set-gcp-credentials && make tests && make coverage
  # command: make set-gcp-credentials && make download_validation && make download_dataset_v2_ipc && make validate_instanovo
  # command: make set-gcp-credentials && make train_acpt
  # command: make set-gcp-credentials && make finetune_on_hcpt
  # command: make set-gcp-credentials && make finetune_on_phospho
  # command: make set-gcp-credentials && make train_extended
  # command: make set-gcp-credentials && make eval_species_zero_shot

  tensorboard: # optional, disabled by default
    enabled: true

  types:
    Worker:
      count: 1
      resources:
        cpus: 32
        ramRatio: 8 # >= 2

        accelerators:
          gpu:
            count: 1
            type: gpu # gpu, mig-1g.10gb, mig-3g.20gb, mig-3g.40gb
            product: NVIDIA-A100-SXM4-80GB # NVIDIA-A100-SXM4-80GB NVIDIA-A100-SXM4-40GB
