# Model parameters
dim_model: 768
n_head: 16
dim_feedforward: 1024
n_layers: 9
dropout: 0.1
use_flash_attention: False
conv_peak_encoder: False

# Model data parameters
n_peaks: 200 # 150
min_mz: 50.0
max_mz: 2500.0
min_intensity: 0.01
remove_precursor_tol: 2.0
max_charge: 10
precursor_mass_tol: 50 # ppm
isotope_error_range: [0, 1]

max_length: 40
