# Spectrum processing options.
n_peaks: 200 # 150
min_mz: 50.0
max_mz: 2500.0
min_intensity: 0.01
remove_precursor_tol: 2.0
max_charge: 10
precursor_mass_tol: 50 # ppm
isotope_error_range: [0, 1]

# Model architecture options.
dim_model: 768
n_head: 16
dim_feedforward: 1024
n_layers: 9
dropout: 0.1
dim_intensity:
custom_encoder:

max_length: 30
residues:
  "G": 57.021464
  "A": 71.037114
  "S": 87.032028
  "P": 97.052764
  "V": 99.068414
  "T": 101.047670
  # "C(+57.02)": 160.030649
  "C": 160.030649 # V1
  "L": 113.084064
  "I": 113.084064
  "N": 114.042927
  "D": 115.026943
  "Q": 128.058578
  "K": 128.094963
  "E": 129.042593
  "M": 131.040485
  "H": 137.058912
  "F": 147.068414
  "R": 156.101111
  "Y": 163.063329
  "W": 186.079313
  # "M(+15.99)": 147.035400
  "M(ox)": 147.035400 # V1
  "N(+.98)": 115.026943
  "Q(+.98)": 129.042594
  "S(p)": 166.998028 # Phosphorylation + 79.966
  "T(p)": 181.01367 # Phosphorylation + 79.966
  "Y(p)": 243.029329 # Phosphorylation + 79.966
n_log: 1
tb_summarywriter: "./logs/instanovo-yeast/instanovo-ft"

warmup_iters: 5_000
max_iters: 3_000_000
learning_rate: 5e-5 #5e-4 5e-5
weight_decay: 1e-5

# Training/inference options.
train_batch_size: 32
grad_accumulation: 1
n_gpu: 1
n_workers: 16
gradient_clip_val: 10.0
predict_batch_size: 64
n_beams: 5

logger:
epochs: 30
num_sanity_val_steps: 10
console_logging_steps: 1000
tensorboard_logging_steps: 200

# Subsets for training and validation set
train_subset: 1.0 # Used for debugging
use_shards: True
train_path: data/denovo_phospho/graphpart/
valid_path: data/denovo_phospho/graphpart/
valid_subset_of_train: 0.1 # If valid_path is not specified, split the training set and save the splits
valid_subset: 0.1 # Speed up training
val_check_interval: 1.0 # 1.0

save_model: True
model_save_folder_path: "checkpoints/instanovo-ft-phospho"
save_weights_only: False
ckpt_interval: 62_779
train_from_scratch: False
resume_checkpoint: "./checkpoints/acpt_ba75cf85/epoch=9-step=8750000.ckpt"
residue_conflict_resolution: partial # delete, random, partial
