# Combination of multiple datasets
# - ACPT
# - Pride
# - Phospho

use_shards: True
train_path: # Unshuffled
  - /mnt/instanovo-data-kyber/identity_splits_parquet/acpt/*-train-*.parquet
  - /mnt/instanovo-data-kyber/identity_splits_parquet/pride/*-train-*.parquet
  - /mnt/instanovo-data-kyber/identity_splits_parquet/phospho/*-train-*.parquet
# train_path: /mnt/instanovo-data-kyber/shuffled/extended/*.parquet # Shuffled
valid_path: /mnt/instanovo-data-kyber/identity_splits_parquet/acpt/*-valid-*.parquet
valid_subset_of_train:
# If any train sequences overlap with the blacklist, raise a ValueError
blacklist: /mnt/instanovo-data-kyber/identity_splits_parquet/blacklist.csv
train_partition:
valid_partition:

column_remapping:

# Left gets remapped to right, right should exist in residue set
residue_remapping:
