defaults:
  - default
  - _self_

# Data paths and output location
data_path:
  - result_name: test
    input_path: tests/instanovo_test_resources/example_data/test_sample.mgf # type: .ipc
    output_path: tests/instanovo_test_resources/test_sample_preds.csv # type: .csv

result_file_path: tests/instanovo_test_resources/instanovo_results.csv # type: .csv

instanovo_model: tests/instanovo_test_resources/model.ckpt # type: .ckpt
output_path: # type: .csv
knapsack_path: tests/instanovo_test_resources/example_knapsack # type: directory
use_knapsack: False

num_beams: 1
max_length: 6
max_charge: 3
denovo: False

subset: 1

batch_size: 32
device: auto
fp16: True

residue_remapping: ""
pred_col: preds
pred_tok_col: preds_tokenised
log_probs_col: log_probs
token_log_probs_col: token_log_probs
