defaults:
  - default
  - _self_

# Data paths and output location
data_path: ./tests/instanovo_test_resources/example_data/test_sample.mgf # type: .ipc
model_path: ./tests/instanovo_test_resources/model.ckpt # type: .ckpt
output_path: ./tests/instanovo_test_resources/test_sample_preds.csv # type: .csv
knapsack_path: ./tests/instanovo_test_resources/example_knapsack # type: directory
use_knapsack: False

num_beams: 5
max_length: 30
max_charge: 3

subset: 1

batch_size: 32
device: cuda
fp16: False

residue_remapping: ""
