defaults:
  - instanovo
  - _self_
  - override dataset: extended
  - override residues: extended
  - override model: instanovo_650M

learning_rate: 5e-5 #5e-4 5e-5
train_batch_size: 64

model_save_folder_path: "checkpoints/instanovo-1b"
