defaults:
  - instanovo
  - _self_
  - override dataset: massivekb
  - override residues: extended_unimod

run_name: instanovo_massivekb
tags:
  - massivekb

learning_rate: 5e-5 #5e-4 5e-5
train_batch_size: 128
preshuffle_shards: False # Using already shuffled shards

model_save_folder_path: "checkpoints/instanovo-massivekb"
