defaults:
  - instanovo
  - _self_
  - override model: instanovo_unit_test
  - override dataset: unit_test
  - override residues: unit_test

# Overwritten when using Aichor
tb_summarywriter: "./logs/instanovo/instanovo-unit-test"

# Training parameters
warmup_iters: 1000
max_iters: 3_000_000
learning_rate: 1e-3
train_batch_size: 32
grad_accumulation: 1

# Logging parameters
logger:
epochs: 5
num_sanity_val_steps: 10
console_logging_steps: 50
tensorboard_logging_steps: 500
report_to:
run_name: instanovo_unit_test

# Training data parameters
valid_subset: 1.0

# Checkpointing parameters
model_save_folder_path: ./tests/instanovo_test_resources/train_test
ckpt_interval: 2420
