defaults:
  - instanovo
  - _self_
  - override model: instanovo_8M
  - override dataset: nine_species
  - override residues: default

# Overwritten when using Aichor
tb_summarywriter: "./logs/instanovo/instanovo-nine-species"

# Training parameters
warmup_iters: 785 # 100
max_iters: 3_000_000
learning_rate: 5e-4
weight_decay: 1e-5
train_batch_size: 32
grad_accumulation: 1
predict_batch_size: 32
n_beams: 5

# Logging parameters
epochs: 5
num_sanity_val_steps: 10
console_logging_steps: 2000
report_to: neptune
run_name: instanovo_nine_species_v1

tags:
  - nine_species_v1
  - "numpy 2.0.2"
  - "pytorch 2.4.1"

# Training data parameters
train_subset: 0.1
valid_subset: 0.01
val_check_interval: 1.0 # This doesn't work

# Checkpointing parameters
model_save_folder_path: "checkpoints/instanovo-nine-species-8M"
ckpt_interval: 7845

subset: 0.01
